N_SERVERS=ENV["N_SERVER"]
# The "2" in the first line below represents the version of the configuration object config that will be used for configuration for that block (the section between the do and the end). This object can be very different from version to version.
Vagrant.configure("2") do |config| 
  

  #N_ loop to create N worker nodes
  (1..N_SERVERS.to_i).each do |i|
    config.vm.define "worker#{i}" do |worker|
     worker.vm.box_download_insecure = true
     worker.vm.box = "hashicorp/bionic64"
     worker.vm.network :private_network, ip: "192.168.56.#{20+i}"
     worker.vm.hostname = "worker#{i}"
     worker.vm.provider "virtualbox" do |v|
      v.name = "worker#{i}"
      v.memory = 2048
      v.cpus = 1
     end   
    end
  end
end
